spring:
  application:
    name: spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:1.5b
        temperature: 0.7
  datasource:
    url: jdbc:mysql://localhost:3306/spring_ai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  ai:
    system-prompt: 你是一名耐心、简洁、适合初学者的Java和Spring AI 学习助手。回答时先给结论，再分步骤解释。
    memory:
      max-messages: 20


server:
  port: 8080

